name: Maven build

jobs:
  build:
    runs-on: euleros-2.10.1
    steps:
    - uses: checkout-action@0.0.1
    - name: Set up JDK 
      uses: setup-java@0.0.1
      with:
        java-version: '8'

    - name: Build with Maven
      run:  cd repo_workspace && mvn -B package --file pom.xml